# Generated by Django 5.2.6 on 2025-12-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_video_ocr_transcript_status_ocrtranscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ocr_index_status',
            field=models.CharField(choices=[('none', 'No Index'), ('indexing', 'Indexing'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='none', max_length=20),
        ),
    ]
