# Generated by Django 5.2.6 on 2025-10-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='content',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='TranscriptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField(blank=True, null=True)),
                ('text', models.TextField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transcripts.transcript')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
